programs:
  sleep:
    cmd: "/bin/sleep 30"
    numprocs: 3
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes: 
      - 0
      - 2
    startretries: 1
    starttime: 4
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/ls.stdout
    stderr: /tmp/ls.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42  
